# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4wunZPHLvv7NaVyoENiqwpWv8APaC2t
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/Salary_Dataset_DataScienceLovers.csv')

df

df.isnull().sum()

for column in df.columns:
  if df[column].dtype == 'object':
    # Fill categorical columns with the mode
    df[column]= df[column].fillna(df[column].mode()[0])
  else:
    # Fill numerical columns with the mean
    df[column] = df[column].fillna(df[column].mean())

print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for column in ['Company Name', 'Location', 'Employment Status', 'Job Roles', 'Job Title']:
  df[column] = label_encoder.fit_transform(df[column])

print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB

# Define features (X) and target (y) AFTER all preprocessing
X = df.drop('Salary', axis=1)
y = df['Salary']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale data (important)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = [LinearRegression(), KNeighborsRegressor(), DecisionTreeRegressor(),
          SVR(), RandomForestRegressor(), GaussianNB()]

for m in models:
    m.fit(X_train, y_train)

print("All models trained successfully")

from sklearn.metrics import mean_absolute_error

results = {}
for i, m in enumerate(models):
    y_pred = m.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    results[type(m).__name__] = mae

# Print evaluation results
for model_name, mae_score in results.items():
    print(f"{model_name}: MAE = {mae_score:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Convert results dictionary to a DataFrame for easy plotting
mae_df = pd.DataFrame(results.items(), columns=['Model', 'MAE'])

# Sort by MAE for better visualization (lowest MAE is best)
mae_df = mae_df.sort_values(by='MAE', ascending=True)

plt.figure(figsize=(12, 7))
sns.barplot(x='Model', y='MAE', hue='Model', data=mae_df, palette='viridis', legend=False)
plt.title('Mean Absolute Error (MAE) for Different Models')
plt.xlabel('Model')
plt.ylabel('Mean Absolute Error')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import joblib

# Identify the best model based on MAE
best_model_name = min(results, key=results.get)
best_model_index = [type(m).__name__ for m in models].index(best_model_name)
best_model = models[best_model_index]

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_model.pkl')
print(f"The best model ({best_model_name}) has been saved as 'best_model.pkl'")
